# Generated by Django 5.2 on 2025-04-22 03:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("concerts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="concert",
            old_name="id",
            new_name="concert_id",
        ),
        migrations.RenameField(
            model_name="location",
            old_name="id",
            new_name="location_id",
        ),
        migrations.RenameField(
            model_name="location",
            old_name="name",
            new_name="location_name",
        ),
        migrations.RenameField(
            model_name="site",
            old_name="id",
            new_name="site_id",
        ),
        migrations.RenameField(
            model_name="site",
            old_name="name",
            new_name="site_name",
        ),
    ]
