# Generated by Django 5.2 on 2025-04-23 07:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("concerts", "0002_rename_id_concert_concert_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="location",
            old_name="location_id",
            new_name="loctaion_id",
        ),
        migrations.RenameField(
            model_name="location",
            old_name="location_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="site",
            old_name="site_name",
            new_name="name",
        ),
    ]
