# Generated by Django 5.2 on 2025-04-23 07:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("concerts", "0003_rename_location_id_location_loctaion_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="location",
            old_name="loctaion_id",
            new_name="location_id",
        ),
    ]
