# Generated by Django 5.2 on 2025-04-23 07:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("concerts", "0004_rename_loctaion_id_location_location_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="location",
            old_name="name",
            new_name="location_name",
        ),
        migrations.RenameField(
            model_name="site",
            old_name="name",
            new_name="site_name",
        ),
    ]
