# Generated by Django 5.2 on 2025-04-21 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='공연장 이름')),
            ],
            options={
                'verbose_name': '공연장',
                'verbose_name_plural': '공연장 목록',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='콘서트 제목')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='시작일')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='종료일')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concerts', to='concerts.location', verbose_name='공연 장소')),
            ],
            options={
                'verbose_name': '콘서트',
                'verbose_name_plural': '콘서트 목록',
                'ordering': ['start_date', 'title'],
            },
        ),
    ]
