# Generated by Django 5.2 on 2025-04-21 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concerts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="concert",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="concerts",
                to="concerts.location",
                verbose_name="콘서트 장소",
            ),
        ),
    ]
