# Generated by Django 5.2 on 2025-04-21 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='사이트 이름')),
            ],
            options={
                'verbose_name': '출처 사이트',
                'verbose_name_plural': '출처 사이트 목록',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='concert',
            name='title',
            field=models.CharField(max_length=200, verbose_name='콘서트 제목'),
        ),
        migrations.AddField(
            model_name='concert',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concerts', to='concerts.site', verbose_name='출처사이트'),
        ),
    ]
