# Generated by Django 5.2 on 2025-04-21 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concerts", "0002_alter_concert_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="Site",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name="location",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name="concert",
            name="site",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="concerts",
                to="concerts.site",
                verbose_name="콘서트 출처",
            ),
        ),
    ]
