# Generated by Django 5.2 on 2025-04-21 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concerts", "0003_site_alter_location_id_concert_site"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="concert",
            options={},
        ),
        migrations.AlterModelOptions(
            name="location",
            options={},
        ),
        migrations.AlterField(
            model_name="concert",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="concert",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="concerts.location"
            ),
        ),
        migrations.AlterField(
            model_name="concert",
            name="site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="concerts.site",
            ),
        ),
        migrations.AlterField(
            model_name="concert",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="concert",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="location",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="site",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
