# Generated by Django 5.2 on 2025-04-21 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allincon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='max_people',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
